2019-06-21 15:10:52,985 ERROR: Exception on /delete_recipe/Fried egg [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\sqlalchemy\sql\selectable.py", line 61, in _interpret_as_from
    return insp.selectable
AttributeError: 'InstanceState' object has no attribute 'selectable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 273, in delete_recipe
    recipe.clear_ingredients()
  File "C:\Python\git\microblog\app\models.py", line 41, in clear_ingredients
    db.delete(ingredient)
  File "<string>", line 2, in delete
  File "c:\python\git\microblog\winvenv\lib\site-packages\sqlalchemy\sql\dml.py", line 861, in __init__
    self.table = _interpret_as_from(table)
  File "c:\python\git\microblog\winvenv\lib\site-packages\sqlalchemy\sql\selectable.py", line 63, in _interpret_as_from
    raise exc.ArgumentError("FROM expression expected")
sqlalchemy.exc.ArgumentError: FROM expression expected
2019-06-21 15:13:16,903 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-06-21 15:14:04,247 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-06-21 15:14:07,667 ERROR: Exception on /delete_recipe/Fried egg [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\sqlalchemy\sql\selectable.py", line 61, in _interpret_as_from
    return insp.selectable
AttributeError: 'InstanceState' object has no attribute 'selectable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 273, in delete_recipe
    db.delete(recipe)
  File "<string>", line 2, in delete
  File "c:\python\git\microblog\winvenv\lib\site-packages\sqlalchemy\sql\dml.py", line 861, in __init__
    self.table = _interpret_as_from(table)
  File "c:\python\git\microblog\winvenv\lib\site-packages\sqlalchemy\sql\selectable.py", line 63, in _interpret_as_from
    raise exc.ArgumentError("FROM expression expected")
sqlalchemy.exc.ArgumentError: FROM expression expected
2019-06-21 15:15:49,583 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-06-21 15:16:22,356 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-06-21 15:22:24,189 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
